#  "elasticsearch-data-skywalking_skywalking-network" --> skywalking-ui network 
version: '3.0'
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    ports: []
    hostname: oauth2-proxy
    container_name: oauth2-proxy
    command: --config /oauth2-proxy.cfg
    volumes:
      - "./oauth2-proxy-nginx.cfg:/oauth2-proxy.cfg"
    networks:
      - elasticsearch-data-skywalking_skywalking-network
  nginx:
    depends_on:
      - oauth2-proxy
    container_name: nginx
    image: nginx:1.27
    restart: unless-stopped
    ports:
      - 1441:80/tcp
    hostname: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - elasticsearch-data-skywalking_skywalking-network

networks:
  elasticsearch-data-skywalking_skywalking-network:
    external: true
